/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authority_buildings.UI;

import Modules.Connection_fun;
import Modules.Get_SQL_Data_ComboBox;
import static authority_buildings.UI.EmployeeLogin.Employee_id;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class Employee_RegisterReport extends javax.swing.JFrame {

    String Report_id_Selection;
    String Condition;

    /**
     * Creates new form Employee_RegisterReport
     */
    public Employee_RegisterReport() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo.png")).getImage();
        this.setIconImage(img);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Register_Report_Button = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Type_Malfunction = new javax.swing.JComboBox<>();
        Update_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Office = new javax.swing.JTextField();
        Floor = new javax.swing.JTextField();
        Refresh = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Description");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Type Malfunction");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        Description.setColumns(20);
        Description.setRows(5);
        jScrollPane1.setViewportView(Description);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 510, 130));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Office");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Floor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        Register_Report_Button.setBackground(new java.awt.Color(0, 0, 0));
        Register_Report_Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Register_Report_Button.setForeground(new java.awt.Color(255, 255, 255));
        Register_Report_Button.setText("Register Report");
        Register_Report_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_Report_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Register_Report_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 340, -1));

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        Type_Malfunction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(Type_Malfunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 510, 40));

        Update_Button.setBackground(new java.awt.Color(0, 0, 0));
        Update_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Update_Button.setForeground(new java.awt.Color(255, 255, 255));
        Update_Button.setText("Update");
        Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 190, 50));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Report ID", "First name ", "Last Name ", "Type of Malfuncition ", "Role ", "Office Number ", "Description", "Condition_Info"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1000, 190));

        Office.setEditable(false);
        Office.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Office.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Office, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 50, 30));

        Floor.setEditable(false);
        Floor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Floor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 50, 30));

        Refresh.setBackground(new java.awt.Color(0, 0, 0));
        Refresh.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Refresh.setForeground(new java.awt.Color(255, 255, 255));
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/refresh.png"))); // NOI18N
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 40, 40));

        Delete_Button.setBackground(new java.awt.Color(0, 0, 0));
        Delete_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Button.setText("Delete Row");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 290, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 630, 110, -1));

        Search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 320, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/Register report ui.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Register_Report_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_Report_ButtonActionPerformed
        try {
            //the connection
            Connection c = Connection_fun.con();

            // Retrieve Location ID
            String Location_id = null;
            PreparedStatement Location_id_statement = c.prepareStatement("SELECT id FROM location WHERE role = ? AND office_number = ?");
            Location_id_statement.setObject(1, Floor.getText());
            Location_id_statement.setObject(2, Office.getText());
            ResultSet Location_id_result = Location_id_statement.executeQuery();

            if (Location_id_result.next()) {
                Location_id = Location_id_result.getString("id");
            } else {
                JOptionPane.showMessageDialog(this, "Location not found.");
            }

            // Retrieve Type of Malfunction ID
            String Type_of_Maflucation_id = null;
            PreparedStatement Type_of_Maflucation_id_statement = c.prepareStatement("SELECT id FROM type_of_malfuncition WHERE type_of_malfuncition = ?");
            Type_of_Maflucation_id_statement.setObject(1, Type_Malfunction.getSelectedItem());
            ResultSet Type_of_Maflucation_result = Type_of_Maflucation_id_statement.executeQuery();

            if (Type_of_Maflucation_result.next()) {
                Type_of_Maflucation_id = Type_of_Maflucation_result.getString("id");
            } else {
                JOptionPane.showMessageDialog(this, "Type of malfunction not found.");
            }

            // Insert the data into REPORTS table 
            PreparedStatement Reports_statement = c.prepareStatement("INSERT INTO REPORTS(ID, STARTDATE, TYPE_OF_MALFUNCITION_ID,Employee_id, LOCATION_ID,Description,Condition_id) VALUES (REPORTS_SEQ.nextval,sysdate,?,?,?,?,1)");
            Reports_statement.setString(1, Type_of_Maflucation_id);
            Reports_statement.setString(2, Employee_id);
            Reports_statement.setString(3, Location_id);
            Reports_statement.setString(4, Description.getText());

            int updateCount = Reports_statement.executeUpdate();

            if (updateCount >= 1) {
                JOptionPane.showMessageDialog(this, "Success");
                Description.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "We Have a issue ");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQL Error:" + ex.getMessage());
        }

    }//GEN-LAST:event_Register_Report_ButtonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new Employee_HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            // Connection and the Statement
            Connection c = Connection_fun.con();
            Statement statement = c.createStatement();

            // Retrieve Location (Role,Office) in the Text
            //First get the Location_id With the Employee_id
            String Location_id = null;
            PreparedStatement Location_id_statement = c.prepareStatement("SELECT Location_id FROM EMPLOYEESPOSITION WHERE ID=?");
            Location_id_statement.setObject(1, Employee_id);
            ResultSet Location_id_ResultSet = Location_id_statement.executeQuery();

            if (Location_id_ResultSet.next()) {
                Location_id = Location_id_ResultSet.getString("Location_id");
            } else {
                JOptionPane.showMessageDialog(this, "Location not found for the employee.");
            }

            //2nd get the (Role,Office) with the Location_id
            if (Location_id != null) {
                PreparedStatement Location_Statement = c.prepareStatement("SELECT Role, Office_number FROM Location WHERE ID=?");
                Location_Statement.setString(1, Location_id);
                ResultSet Location_ResultSet = Location_Statement.executeQuery();

                if (Location_ResultSet.next()) {
                    // 3nd Set (Role,Office) in Text
                    Floor.setText(Location_ResultSet.getString("Role"));
                    Office.setText(Location_ResultSet.getString("Office_number"));
                } else {
                    JOptionPane.showMessageDialog(this, "No location details found.");
                }
            }
            //Put the Register_Report Table data with the id
            // Table Code
            DefaultTableModel TableModels = (DefaultTableModel) Table.getModel();
            TableModels.setRowCount(0);  // Clear the table

            // Execute the query and retrieve the result set
            PreparedStatement Reports_Table = c.prepareStatement("select report_id,employee_first_name,employee_last_name,malfunction_type,location_role,location_office_number,report_description,condition_status from Register_Report Where Employee_id =? and Condition_Status = 'Available' ");
            Reports_Table.setString(1, Employee_id);
            ResultSet Result = Reports_Table.executeQuery();
            ResultSetMetaData metaData = Result.getMetaData();
            int columnCount = metaData.getColumnCount();
            Object[] Array_Tabel;

            // Create a Array and Put The Table Data on it.
            while (Result.next()) {

                Array_Tabel = new Object[columnCount];

                for (int i = 0; i < columnCount; i++) {
                    // Retrieve the object and check if it is NULL
                    Object value = Result.getObject(i + 1);

                    // If the value is NULL
                    Array_Tabel[i] = (value != null) ? value : "N/A";
                }

                // Add the row to the table model
                TableModels.addRow(Array_Tabel);
            }

            //Put All TYPE_OF_MALFUNCITION data to the ComboBox using the Get_SQL_Data_ComboBox Function
            new Get_SQL_Data_ComboBox("select count(*) from TYPE_OF_MALFUNCITION", "select type_of_malfuncition from TYPE_OF_MALFUNCITION", "type_of_malfuncition", Type_Malfunction);
        } catch (SQLException ex) {
            Logger.getLogger(Employee_RegisterReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // Get the selected row index in the table
        int selectedRow = Table.getSelectedRow();

        // Put the selected row index from the view to the model
        int modelRow = Table.convertRowIndexToModel(selectedRow);

        // Get the DefaultTableModel
        DefaultTableModel tbmodel = (DefaultTableModel) Table.getModel();

        // Use the modelRow to get the data from the correct row in the model
        Report_id_Selection = tbmodel.getValueAt(modelRow, 0).toString();
        String Type_of_Malfunction = tbmodel.getValueAt(modelRow, 3).toString();
        String Role = tbmodel.getValueAt(modelRow, 4).toString();
        String Office = tbmodel.getValueAt(modelRow, 5).toString();
        String Description = tbmodel.getValueAt(modelRow, 6).toString();
        Condition = tbmodel.getValueAt(modelRow, 7).toString();

        // Put the data in the ComboBox and Text fields
        Type_Malfunction.setSelectedItem(Type_of_Malfunction);
        Floor.setText(Role);
        this.Office.setText(Office);
        this.Description.setText(Description);
    }//GEN-LAST:event_TableMouseClicked

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ButtonActionPerformed
        if (Table.getSelectedRow() == -1) {
            // No row selected, show message
            JOptionPane.showMessageDialog(this, "No row selected. Please select the row to update.");
        } else {
            try {
                //Connection
                Connection c = Connection_fun.con();
                Statement statement = c.createStatement();

                // Retrieve Location ID
                String Location_id = null;
                PreparedStatement Location_id_statement = c.prepareStatement("SELECT id FROM location WHERE role = ? AND office_number = ?");
                Location_id_statement.setObject(1, Floor.getText());
                Location_id_statement.setObject(2, Office.getText());
                ResultSet Location_id_result = Location_id_statement.executeQuery();

                if (Location_id_result.next()) {
                    Location_id = Location_id_result.getString("id");
                } else {
                    JOptionPane.showMessageDialog(this, "Location not found.");
                }

                // Retrieve Type of Malfunction ID
                String Type_of_Maflucation_id = null;
                PreparedStatement Type_of_Maflucation_id_statement = c.prepareStatement("SELECT id FROM type_of_malfuncition WHERE type_of_malfuncition = ?");
                Type_of_Maflucation_id_statement.setObject(1, Type_Malfunction.getSelectedItem());
                ResultSet Type_of_Maflucation_result = Type_of_Maflucation_id_statement.executeQuery();

                if (Type_of_Maflucation_result.next()) {
                    Type_of_Maflucation_id = Type_of_Maflucation_result.getString("id");
                } else {
                    JOptionPane.showMessageDialog(this, "Type of malfunction not found.");
                }

                //Update the Table
                PreparedStatement UPDATE_Register_Report = c.prepareStatement("UPDATE Reports SET Type_of_Malfuncition_id=?, Location_ID=?, Description=? WHERE ID=?");
                UPDATE_Register_Report.setObject(1, Type_of_Maflucation_id);
                UPDATE_Register_Report.setObject(2, Location_id);
                UPDATE_Register_Report.setString(3, Description.getText());
                UPDATE_Register_Report.setString(4, Report_id_Selection);

                int updateCount = UPDATE_Register_Report.executeUpdate();
                if (updateCount >= 1) {
                    JOptionPane.showMessageDialog(this, "Success");
                    Description.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "No ID Selected,Please Select the row you need to Update");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Employee_RegisterReport.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_Update_ButtonActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        try {
            // Connection and the Statement
            Connection c = Connection_fun.con();
            // Table Code
            DefaultTableModel TableModels = (DefaultTableModel) Table.getModel();
            TableModels.setRowCount(0);  // Clear the table

            // Execute the query and retrieve the result set
            PreparedStatement Reports_Table = c.prepareStatement("select report_id,employee_first_name,employee_last_name,malfunction_type,location_role,location_office_number,report_description,condition_status from Register_Report Where Employee_id =? and Condition_Status = 'Available' ");
            Reports_Table.setString(1, Employee_id);
            ResultSet Result = Reports_Table.executeQuery();
            ResultSetMetaData metaData = Result.getMetaData();
            int columnCount = metaData.getColumnCount();
            Object[] Array_Tabel;

            // Create a Array and Put The Table Data on it.
            while (Result.next()) {

                Array_Tabel = new Object[columnCount];

                for (int i = 0; i < columnCount; i++) {
                    // Retrieve the object and check if it is NULL
                    Object value = Result.getObject(i + 1);

                    // If the value is NULL
                    Array_Tabel[i] = (value != null) ? value : "N/A";
                }

                // Add the row to the table model
                TableModels.addRow(Array_Tabel);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employee_RegisterReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        try {
            //Connection
            Connection c = Connection_fun.con();
            int Delete = JOptionPane.showConfirmDialog(rootPane, "Are You Sure Delete this row", "Delete", JOptionPane.YES_NO_OPTION);
            //IF JOptionPane
            if (Delete == JOptionPane.YES_OPTION) {

                // delete the Report
                PreparedStatement Employees_statement = c.prepareStatement("DELETE FROM Reports WHERE id=?");
                Employees_statement.setString(1, Report_id_Selection);
                int updateCount_EmployeePosition = Employees_statement.executeUpdate();

                if (updateCount_EmployeePosition >= 1) {
                    JOptionPane.showMessageDialog(this, "Success");
                } else {
                    JOptionPane.showMessageDialog(this, "We Have an issue ");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        DefaultTableModel ob = (DefaultTableModel) Table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        Table.setRowSorter(obj);
        obj.setRowFilter(javax.swing.RowFilter.regexFilter(Search.getText()));
    }//GEN-LAST:event_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_RegisterReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_RegisterReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_RegisterReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_RegisterReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_RegisterReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextField Floor;
    private javax.swing.JTextField Office;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Register_Report_Button;
    private javax.swing.JTextField Search;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> Type_Malfunction;
    private javax.swing.JButton Update_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
