/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authority_buildings.UI;

import Modules.Connection_fun;
import Modules.Get_SQL_Data_ComboBox;
import Modules.Get_TABLE_Data;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class Responsible_Add_Delete extends javax.swing.JFrame {

    String id_Selection_Delete;
    String Employee_id;

    /**
     * Creates new form Responsible_AddTechnical
     */
    public Responsible_Add_Delete() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo.png")).getImage();
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        User_Name = new javax.swing.JTextField();
        Last_Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        position = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        office = new javax.swing.JComboBox<>();
        role = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Add_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        First_Name = new javax.swing.JTextField();
        Delete_Button = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ShowPassword = new javax.swing.JRadioButton();
        ShowPassword1 = new javax.swing.JRadioButton();
        Confirm_Password = new javax.swing.JPasswordField();
        Password = new javax.swing.JPasswordField();
        Update_Button = new javax.swing.JButton();
        Search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Update_Button1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        User_Name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(User_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 510, -1));

        Last_Name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(Last_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 510, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Last Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("UserName");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 220, 40));

        Refresh.setBackground(new java.awt.Color(0, 0, 0));
        Refresh.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Refresh.setForeground(new java.awt.Color(255, 255, 255));
        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/refresh.png"))); // NOI18N
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 660, 40, 40));

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        position.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Employee", "Technical" }));
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });
        getContentPane().add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 120, -1));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Employee Type", "User Name", "Password", "Role", "Office"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 1000, 150));

        office.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(office, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, -1, -1));

        role.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Office");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 80, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Search");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 630, 110, -1));

        Add_Button.setBackground(new java.awt.Color(0, 0, 0));
        Add_Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Add_Button.setForeground(new java.awt.Color(255, 255, 255));
        Add_Button.setText("Add Technical");
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Add_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 640, 290, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("First Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        First_Name.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(First_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 510, -1));

        Delete_Button.setBackground(new java.awt.Color(0, 0, 0));
        Delete_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Button.setText("Delete Row");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 660, 290, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        ShowPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ShowPassword.setText("Show Password");
        ShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, 170, -1));

        ShowPassword1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ShowPassword1.setText("Show Password");
        ShowPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowPassword1ActionPerformed(evt);
            }
        });
        getContentPane().add(ShowPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 170, -1));

        Confirm_Password.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(Confirm_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 510, -1));

        Password.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 510, -1));

        Update_Button.setBackground(new java.awt.Color(0, 0, 0));
        Update_Button.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Update_Button.setForeground(new java.awt.Color(255, 255, 255));
        Update_Button.setText("Update Employee");
        Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, 290, -1));

        Search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 320, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Role");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, 80, -1));

        Update_Button1.setBackground(new java.awt.Color(0, 0, 0));
        Update_Button1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Update_Button1.setForeground(new java.awt.Color(255, 255, 255));
        Update_Button1.setText("Clear Data");
        Update_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 580, 290, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/add_technical.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        try {
            new Get_TABLE_Data("select* from Employee_Table ORDER by id Asc",
                    Table);
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_AddFloor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefreshActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new Responsible_Settings().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        try {
            new Get_SQL_Data_ComboBox("select Max(Role) from location", "select DISTINCT Role from location order by role ASC", "Role", role);
            new Get_SQL_Data_ComboBox("select Max(Office_number) from location", "select DISTINCT Office_number from location order by Office_number ASC", "Office_number", office);
            new Get_TABLE_Data("select* from Employee_Table ORDER by id Asc", Table);
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        String selectedPosition = (String) position.getSelectedItem();

        // Check if the selected position is "Employee"
        if ("Employee".equals(selectedPosition) || "Admin".equals(selectedPosition)) {
            // Disable the role and office combo boxes
            role.setEnabled(true);
            office.setEnabled(true);
        } else {
            // Enable the role and office combo boxes for other selections
            role.setEnabled(false);
            office.setEnabled(false);
        }
    }//GEN-LAST:event_positionActionPerformed

    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed

        try {
            // Establish the connection
            Connection c = Connection_fun.con();
            Statement statement = c.createStatement();

            // Ensure password matches
            if (!Password.getText().equals(Confirm_Password.getText())) {
                JOptionPane.showMessageDialog(this, "The Password does not match the Confirm Password. Please confirm your password.");
                return; // Exit if passwords don't match
            }

            // Check if the position is "Technical"
            if ("Technical".equals(position.getSelectedItem())) {
                PreparedStatement Employees_statement = c.prepareStatement("INSERT INTO EmployeesPosition VALUES(Add_Employee_id_SEQ.nextval,?,?,?,?,?,NULL)");
                Employees_statement.setString(1, First_Name.getText());
                Employees_statement.setString(2, Last_Name.getText());
                Employees_statement.setObject(3, position.getSelectedItem());
                Employees_statement.setString(4, User_Name.getText());
                Employees_statement.setString(5, Confirm_Password.getText());

                int updateCount = Employees_statement.executeUpdate();
                if (updateCount >= 1) {
                    JOptionPane.showMessageDialog(this, "Employee added successfully.");
                    clearFormFields(); // Clear the form after a successful insert
                } else {
                    JOptionPane.showMessageDialog(this, "There was an issue adding the employee.");
                }
            } else {
                // Retrieve Location ID
                String Location_id = null;
                PreparedStatement Location_id_statement = c.prepareStatement("SELECT id FROM location WHERE role = ? AND office_number = ?");
                Location_id_statement.setObject(1, role.getSelectedItem());
                Location_id_statement.setObject(2, office.getSelectedItem());
                ResultSet Location_id_result = Location_id_statement.executeQuery();

                if (Location_id_result.next()) {
                    Location_id = Location_id_result.getString("id");

                    // Check if the location is already assigned to another employee
                    PreparedStatement CheckLocation = c.prepareCall("SELECT COUNT(*) AS count FROM EmployeesPosition WHERE Location_id = ?");
                    CheckLocation.setString(1, Location_id);
                    ResultSet CheckLocationResult = CheckLocation.executeQuery();

                    if (CheckLocationResult.next() && CheckLocationResult.getInt("count") > 0) {
                        JOptionPane.showMessageDialog(this, "This location is already associated with an employee.");
                    } else {
                        // Check if Username or Password is already used
                        int Username_Check = 0;
                        int Password_Check = 0;

                        PreparedStatement Check_Employees_statement = c.prepareStatement("SELECT COUNT(User_Name) AS UserName_Check, COUNT(Password) AS Password_Check FROM EmployeesPosition WHERE User_Name = ? OR Password = ?");
                        Check_Employees_statement.setString(1, User_Name.getText());
                        Check_Employees_statement.setString(2, Confirm_Password.getText());  // Fix: Bind the second parameter for the password

                        ResultSet Result = Check_Employees_statement.executeQuery();
                        if (Result.next()) {
                            Username_Check = Result.getInt("UserName_Check");
                            Password_Check = Result.getInt("Password_Check");
                        }

                        if (Username_Check == 0 && Password_Check == 0) {
                            // Insert the new employee
                            PreparedStatement Employees_statement = c.prepareStatement("INSERT INTO EmployeesPosition VALUES(Add_Employee_id_SEQ.nextval,?,?,?,?,?,?)");
                            Employees_statement.setString(1, First_Name.getText());
                            Employees_statement.setString(2, Last_Name.getText());
                            Employees_statement.setObject(3, position.getSelectedItem());
                            Employees_statement.setString(4, User_Name.getText());
                            Employees_statement.setString(5, Confirm_Password.getText());
                            Employees_statement.setString(6, Location_id);

                            int updateCount = Employees_statement.executeUpdate();
                            if (updateCount >= 1) {
                                JOptionPane.showMessageDialog(this, "Employee added successfully.");
                                clearFormFields();  // Clear the form after a successful insert
                            } else {
                                JOptionPane.showMessageDialog(this, "There was an issue adding the employee.");
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "The username or password is already used.");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Location not found.");
                }
            }

            //Delete Row
            int getValue = Table.getSelectedRow();
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Add_ButtonActionPerformed

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        try {
            // Connection
            Connection c = Connection_fun.con();

            int deleteConfirmation = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete this row?", "Delete", JOptionPane.YES_NO_OPTION);

            if (deleteConfirmation == JOptionPane.YES_OPTION) {
                // Check if the selected position is "Technical"
                if ("Technical".equals(position.getSelectedItem())) {
                    // Update the child records in Reports table to set Technical_id to NULL
                    PreparedStatement updateChildStatement = c.prepareStatement("UPDATE Reports SET Technical_id = NULL WHERE Technical_id = ?");
                    updateChildStatement.setString(1, id_Selection_Delete);
                    updateChildStatement.executeUpdate();
                } else {
                    // If not "Technical", set both Employee_id and Location_id to NULL
                    PreparedStatement updateChildStatement = c.prepareStatement("UPDATE Reports SET Employee_id = NULL, Location_id = NULL WHERE Employee_id = ?");
                    updateChildStatement.setString(1, id_Selection_Delete);
                    updateChildStatement.executeUpdate();
                }

                // Now delete the employee record from EmployeesPosition table
                PreparedStatement employeesStatement = c.prepareStatement("DELETE FROM EmployeesPosition WHERE id = ?");
                employeesStatement.setString(1, id_Selection_Delete);
                int updateCountEmployeePosition = employeesStatement.executeUpdate();

                // Check if the deletion was successful
                if (updateCountEmployeePosition >= 1) {
                    JOptionPane.showMessageDialog(this, "Employee deleted successfully.");
                    clearFormFields();
                } else {
                    JOptionPane.showMessageDialog(this, "There was an issue deleting the employee.");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        try {
            // Get the selected row index in the table
            int selectedRow = Table.getSelectedRow();

            // Put the selected row index from the view to the model
            int modelRow = Table.convertRowIndexToModel(selectedRow);

            // Get the value
            id_Selection_Delete = Table.getModel().getValueAt(modelRow, 0).toString();

            // Retrieve other data from the selected row in the model
            DefaultTableModel tbmodel = (DefaultTableModel) Table.getModel();
            Employee_id = tbmodel.getValueAt(modelRow, 0).toString();
            String firstName = tbmodel.getValueAt(modelRow, 1).toString();
            String lastName = tbmodel.getValueAt(modelRow, 2).toString();
            String userName = tbmodel.getValueAt(modelRow, 4).toString();
            String password = tbmodel.getValueAt(modelRow, 5).toString();
            String positionValue = tbmodel.getValueAt(modelRow, 3).toString();
            String roleValue = tbmodel.getValueAt(modelRow, 6).toString();
            String officeValue = tbmodel.getValueAt(modelRow, 7).toString();

            // Set the data to the corresponding text fields
            First_Name.setText(firstName);
            Last_Name.setText(lastName);
            User_Name.setText(userName);
            Password.setText(password);
            Confirm_Password.setText(password);
            position.setSelectedItem(positionValue);
            role.setSelectedItem(roleValue);
            office.setSelectedItem(officeValue);

        } catch (Exception ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_TableMouseClicked

    private void ShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPasswordActionPerformed
        if (ShowPassword.isSelected()) {
            Confirm_Password.setEchoChar((char) 0);
        } else {
            Confirm_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPasswordActionPerformed

    private void ShowPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowPassword1ActionPerformed
        if (ShowPassword1.isSelected()) {
            Password.setEchoChar((char) 0);
        } else {
            Password.setEchoChar('*');
        }
    }//GEN-LAST:event_ShowPassword1ActionPerformed

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ButtonActionPerformed
        try {
            // Connection setup
            Connection c = Connection_fun.con();

            // Get the selected location's ID based on the role and office number
            String Location_id = null;
            PreparedStatement Location_id_statement = c.prepareStatement("SELECT id FROM location WHERE role = ? AND office_number = ?");
            Location_id_statement.setObject(1, role.getSelectedItem());
            Location_id_statement.setObject(2, office.getSelectedItem());
            ResultSet Location_id_result = Location_id_statement.executeQuery();

            if (Location_id_result.next()) {
                Location_id = Location_id_result.getString("id");
            } else {
                JOptionPane.showMessageDialog(this, "Location not found.");
                return; // Exit if location is not found
            }

            // Ensure password matches
            if (!Password.getText().equals(Confirm_Password.getText())) {
                JOptionPane.showMessageDialog(this, "The password and confirm password do not match. Please try again.");
                return; // Exit if passwords do not match
            }

            // Determine whether the position is "Technical"
            PreparedStatement UPDATE_Employee;
            if ("Technical".equals(position.getSelectedItem())) {
                // For technical employees, set Location_id to null
                UPDATE_Employee = c.prepareStatement("UPDATE EmployeesPosition SET First_name = ?, Last_Name = ?, User_Name = ?, Password = ?, Employee_Type = ?, Location_ID = NULL WHERE id = ?");
            } else {
                // For non-technical employees, set Location_id from the fetched value
                UPDATE_Employee = c.prepareStatement("UPDATE EmployeesPosition SET First_name = ?, Last_Name = ?, User_Name = ?, Password = ?, Employee_Type = ?, Location_ID = ? WHERE id = ?");
                UPDATE_Employee.setString(6, Location_id); // Bind Location_id
            }

            // Bind the common parameters for both cases
            UPDATE_Employee.setString(1, First_Name.getText());
            UPDATE_Employee.setString(2, Last_Name.getText());
            UPDATE_Employee.setString(3, User_Name.getText());
            UPDATE_Employee.setString(4, Password.getText());
            UPDATE_Employee.setObject(5, position.getSelectedItem());
            UPDATE_Employee.setString(6, Employee_id);

            // Execute the update
            int updateCount = UPDATE_Employee.executeUpdate();
            if (updateCount >= 1) {
                JOptionPane.showMessageDialog(this, "Employee updated successfully.");
                clearFormFields();
            } else {
                JOptionPane.showMessageDialog(this, "There was an issue updating the employee.");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Update_ButtonActionPerformed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        DefaultTableModel ob = (DefaultTableModel) Table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        Table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(Search.getText()));
    }//GEN-LAST:event_SearchKeyReleased

    private void Update_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_Button1ActionPerformed
        clearFormFields();
    }//GEN-LAST:event_Update_Button1ActionPerformed

    private void clearFormFields() {
        First_Name.setText("");
        Last_Name.setText("");
        User_Name.setText("");
        Password.setText("");
        Confirm_Password.setText("");
        position.setSelectedItem("Admin");
        role.setSelectedItem("1");
        office.setSelectedItem("1");
        Table.clearSelection();
        Search.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Responsible_Add_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Responsible_Add_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Responsible_Add_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Responsible_Add_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Responsible_Add_Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Button;
    private javax.swing.JButton Back;
    private javax.swing.JPasswordField Confirm_Password;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JTextField First_Name;
    private javax.swing.JTextField Last_Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JButton Refresh;
    private javax.swing.JTextField Search;
    private javax.swing.JRadioButton ShowPassword;
    private javax.swing.JRadioButton ShowPassword1;
    private javax.swing.JTable Table;
    private javax.swing.JButton Update_Button;
    private javax.swing.JButton Update_Button1;
    private javax.swing.JTextField User_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> office;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JComboBox<String> role;
    // End of variables declaration//GEN-END:variables
}
