/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authority_buildings.UI;

import Modules.Connection_fun;
import Modules.Get_TABLE_Data;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class Responsible_AddFloor extends javax.swing.JFrame {

    String Role_Delete;
    String Office_Delete;
    String Role_Selection;
    String Floor_Selection;

    /**
     * Creates new form Responsible_AddFloor
     */
    public Responsible_AddFloor() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo.png")).getImage();
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Office = new javax.swing.JTextField();
        Floor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Add_Button = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        Refresh_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        Update_Button = new javax.swing.JButton();
        Search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Office.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(Office, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 510, 50));

        Floor.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 510, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("Office");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Floor");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        Add_Button.setBackground(new java.awt.Color(0, 0, 0));
        Add_Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Add_Button.setForeground(new java.awt.Color(255, 255, 255));
        Add_Button.setText("Add Floor");
        Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Add_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 580, 310, -1));

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/back.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Floor", "Office", "Employee Name"
            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 320, 160));

        Refresh_Button.setBackground(new java.awt.Color(0, 0, 0));
        Refresh_Button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Refresh_Button.setForeground(new java.awt.Color(255, 255, 255));
        Refresh_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/refresh.png"))); // NOI18N
        Refresh_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, 40, 40));

        Delete_Button.setBackground(new java.awt.Color(0, 0, 0));
        Delete_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delete_Button.setForeground(new java.awt.Color(255, 255, 255));
        Delete_Button.setText("Delete Row");
        Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Delete_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 465, 160, 30));

        Update_Button.setBackground(new java.awt.Color(0, 0, 0));
        Update_Button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Update_Button.setForeground(new java.awt.Color(255, 255, 255));
        Update_Button.setText("Update Employee");
        Update_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 465, 160, 30));

        Search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 320, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/add a floor or office ui.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ButtonActionPerformed
        try {
            //Connection
            Connection c = Connection_fun.con();

            //The Insert into the Location Table
            PreparedStatement CheckLocation = c.prepareCall("SELECT COUNT(*) AS count FROM Location WHERE role=? and office_number=?");
            CheckLocation.setString(1, Floor.getText());
            CheckLocation.setString(2, Office.getText());
            ResultSet CheckLocationResult = CheckLocation.executeQuery();

            //If the location is existing
            if (CheckLocationResult.next() && CheckLocationResult.getInt("count") > 0) {
                JOptionPane.showMessageDialog(this, "Location is already exists");
            } else {
                PreparedStatement Add_Floor_Office_Statement = c.prepareStatement("INSERT INTO location VALUES (ADD_FLOOR_SEQ.nextval,?,?)");
                Add_Floor_Office_Statement.setString(1, Floor.getText());
                Add_Floor_Office_Statement.setString(2, Office.getText());
                int updateCount = Add_Floor_Office_Statement.executeUpdate();

                if (updateCount >= 1) {
                    JOptionPane.showMessageDialog(this, "Success");
                } else {
                    JOptionPane.showMessageDialog(this, "We Have a issue ");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_AddFloor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Add_ButtonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        new Responsible_Settings().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Refresh_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_ButtonActionPerformed
        try {
            new Get_TABLE_Data("select * from Location_Employee_View  order by location_role , Location_office_number asc",
                    Table);
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_AddFloor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Refresh_ButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            new Get_TABLE_Data("select * from Location_Employee_View  order by location_role , Location_office_number asc",
                    Table);
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_AddFloor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_ButtonActionPerformed
        try {
            //Connection
            Connection c = Connection_fun.con();

            int Delete = JOptionPane.showConfirmDialog(rootPane, "Are You Sure Delete this row", "Delete", JOptionPane.YES_NO_OPTION);

            //IF JOptionPane
            if (Delete == JOptionPane.YES_OPTION) {

                // First, delete the child records that reference the employee
                PreparedStatement deleteChildStatement = c.prepareStatement("DELETE FROM Location WHERE Role = ? and Office_number = ?");
                deleteChildStatement.setString(1, Role_Delete);
                deleteChildStatement.setString(2, Office_Delete);
                int updateCount_EmployeePosition = deleteChildStatement.executeUpdate();
                if (updateCount_EmployeePosition >= 1) {
                    JOptionPane.showMessageDialog(this, "Success");
                } else {
                    JOptionPane.showMessageDialog(this, "We Have an issue ");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Delete_ButtonActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        try {
            // Get the selected row index in the table
            int selectedRow = Table.getSelectedRow();

            // Put the selected row index from the view to the model
            int modelRow = Table.convertRowIndexToModel(selectedRow);

            // Get the Value in the row and column selection
            Role_Selection = Table.getModel().getValueAt(modelRow, 0).toString();
            Floor_Selection = Table.getModel().getValueAt(modelRow, 1).toString();

            // Put the selection in the id_Selection_Delete variable
            Connection c = Connection_fun.con();
            PreparedStatement ID_Statement = c.prepareStatement("SELECT location_role, Location_office_number FROM Location_Employee_View WHERE location_role = ? AND Location_office_number = ?");
            ID_Statement.setString(1, Role_Selection);
            ID_Statement.setString(2, Floor_Selection);
            ResultSet Test = ID_Statement.executeQuery();

            if (Test.next()) {
                Role_Delete = Test.getString("location_role");
                Office_Delete = Test.getString("Location_office_number");
            }

            // Set the data to the corresponding text fields
            Floor.setText(Role_Selection);
            Office.setText(Floor_Selection);

        } catch (SQLException ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TableMouseClicked

    private void Update_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_ButtonActionPerformed
        try {
            // Connection
            Connection c = Connection_fun.con();
            Statement statement = c.createStatement();

            // Get the location selection
            String Location_id = null;
            PreparedStatement Location_id_statement = c.prepareStatement("SELECT id FROM location WHERE role = ? AND office_number = ?");
            Location_id_statement.setString(1, Role_Selection);
            Location_id_statement.setString(2, Floor_Selection);
            ResultSet Location_id_result = Location_id_statement.executeQuery();

            if (Location_id_result.next()) {
                Location_id = Location_id_result.getString("id");
            } else {
                JOptionPane.showMessageDialog(this, "Location not found.");
            }
            //The Insert into the Location Table
            PreparedStatement CheckLocation = c.prepareCall("SELECT COUNT(*) AS count FROM Location WHERE role=? and office_number=?");
            CheckLocation.setString(1, Floor.getText());
            CheckLocation.setString(2, Office.getText());
            ResultSet CheckLocationResult = CheckLocation.executeQuery();
            
            //If the location is existing
            if (CheckLocationResult.next() && CheckLocationResult.getInt("count") > 0) {
                JOptionPane.showMessageDialog(this, "Location is already exists");
            } else {
                
                // Update the location
                PreparedStatement Update_Location = c.prepareStatement("UPDATE Location SET role = ?, office_number = ? WHERE id = ?");
                Update_Location.setString(1, Floor.getText());
                Update_Location.setString(2, Office.getText());
                Update_Location.setString(3, Location_id);

                int updateCount = Update_Location.executeUpdate();

                if (updateCount >= 1) {
                    JOptionPane.showMessageDialog(this, "Update Successful");
                    Floor.setText("");
                    Office.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "We have an issue updating the location.");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Responsible_Add_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Update_ButtonActionPerformed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        DefaultTableModel ob = (DefaultTableModel) Table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        Table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(Search.getText()));
    }//GEN-LAST:event_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Responsible_AddFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Responsible_AddFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Responsible_AddFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Responsible_AddFloor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Responsible_AddFloor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Button;
    private javax.swing.JButton Back;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JTextField Floor;
    private javax.swing.JTextField Office;
    private javax.swing.JButton Refresh_Button;
    private javax.swing.JTextField Search;
    private javax.swing.JTable Table;
    private javax.swing.JButton Update_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
