/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package authority_buildings.UI;

import Modules.Connection_fun;
import Modules.Get_SQL_Data_ComboBox;
import Modules.Get_TABLE_Data;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Administrator
 */
public class Technical_MaintenanceInformation extends javax.swing.JFrame {

    DefaultListModel ListModel = new DefaultListModel();
    int TotalCost;

    /**
     * Creates new form Technical_MaintenanceInformation
     */
    public Technical_MaintenanceInformation() {
        initComponents();
        Image img = new ImageIcon(this.getClass().getResource("logo.png")).getImage();
        this.setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Technical_Name = new javax.swing.JComboBox<>();
        Cost = new javax.swing.JTextField();
        Report_id_Text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Office = new javax.swing.JTextField();
        Floor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Total = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Spare_Parts_List_Total = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Spare_Parts_List = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Report ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 150, -1));

        Submit.setBackground(new java.awt.Color(0, 0, 0));
        Submit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Submit.setForeground(new java.awt.Color(255, 255, 255));
        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 310, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/back.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Technical Names");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        Table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Report ID", "Start Date", "Description", "Role", "Office", "Condition State", "Employee Name", "Type of Malfuncition "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 960, 160));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/refresh.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 40, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Office");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 150, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Spare Parts");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        Technical_Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(Technical_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 510, 40));

        Cost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cost.setEnabled(false);
        getContentPane().add(Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 100, 40));

        Report_id_Text.setEditable(false);
        Report_id_Text.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Report_id_Text.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Report_id_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 60, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" Select the report you want to manage.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, -1, -1));

        Office.setEditable(false);
        Office.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Office.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Office, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 60, 50));

        Floor.setEditable(false);
        Floor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Floor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Floor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 60, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Floor");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 150, -1));

        Add.setBackground(new java.awt.Color(0, 0, 0));
        Add.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 180, 40));

        Delete.setBackground(new java.awt.Color(0, 0, 0));
        Delete.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 180, 40));

        Total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Total.setEnabled(false);
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 100, 40));

        Spare_Parts_List_Total.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Spare_Parts_List_Total.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(Spare_Parts_List_Total);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 220, 150));

        Spare_Parts_List.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Spare_Parts_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Spare_Parts_List.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                Spare_Parts_ListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(Spare_Parts_List);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 220, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Total Cost");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Selection Cost");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Search");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 110, -1));

        Search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Search.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, 320, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/authority_buildings/UI_Images/Maintenance information management ui.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        if (Report_id_Text.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Select The Report You Need to Manage");
        } else {
            try {
                //Connection
                Connection c = Connection_fun.con();

                // Get the list model from Spare_Parts_List_Total
                ListModel<String> model = Spare_Parts_List_Total.getModel();

                // Concatenate all items into a single string, separated by commas
                StringBuilder concatenatedSpareParts = new StringBuilder();

                for (int i = 0; i < model.getSize(); i++) {
                    String item = model.getElementAt(i);
                    concatenatedSpareParts.append(item);

                    // Add a comma if it's not the last item
                    if (i < model.getSize() - 1) {
                        concatenatedSpareParts.append(", ");
                    }
                }

                // Prepare the SQL statement to insert the concatenated string into the CLOB column
                PreparedStatement ListSpare = c.prepareStatement("INSERT INTO Sub_Total VALUES(Sub_Total_SEQ.NEXTVAL,?,?,?)");

                // Set the concatenated string as the value for the CLOB
                ListSpare.setString(1, Report_id_Text.getText());
                ListSpare.setString(2, concatenatedSpareParts.toString());
                ListSpare.setString(3, Total.getText());

                // Execute the insertion
                ListSpare.executeQuery();

                //Get the Sub_Total With the Report_id Selection
                String ListSpare_id = null;
                PreparedStatement Sub_Total_id = c.prepareStatement("Select ID from Sub_Total Where Report_id = ?");
                Sub_Total_id.setString(1, Report_id_Text.getText());
                ResultSet Sub_Total_Result = Sub_Total_id.executeQuery();
                if (Sub_Total_Result.next()) {
                    ListSpare_id = Sub_Total_Result.getString("ID");
                } else {
                    JOptionPane.showMessageDialog(this, "Sub Total ID Name not found.");
                }

                //Get The Technical ID With the Name Selection.
                String Technical_Name_id = null;
                PreparedStatement Technical_id = c.prepareStatement("SELECT ID FROM EmployeesPosition WHERE First_Name || ' ' || Last_Name =? AND Employee_type = 'Technical'");
                Technical_id.setObject(1, Technical_Name.getSelectedItem());
                ResultSet Technical_id_Result = Technical_id.executeQuery();
                if (Technical_id_Result.next()) {
                    Technical_Name_id = Technical_id_Result.getString("ID");
                } else {
                    JOptionPane.showMessageDialog(this, "Technical Name not found.");
                }

                // Retrieve Location ID
                String Location_id = null;
                PreparedStatement Location_id_statement = c.prepareStatement("SELECT id FROM location WHERE role = ? AND office_number = ?");
                Location_id_statement.setString(1, Floor.getText());
                Location_id_statement.setString(2, Office.getText());
                ResultSet Location_id_result = Location_id_statement.executeQuery();

                if (Location_id_result.next()) {
                    Location_id = Location_id_result.getString("id");
                } else {
                    JOptionPane.showMessageDialog(this, "Location not found.");
                }

                //Set the data from Technical
                PreparedStatement Update_Reports_statement = c.prepareStatement("UPDATE Reports SET EndDate =sysdate,Condition_ID =3,Technical_id=?,Sub_Total_id=? WHERE ID =?");
                Update_Reports_statement.setInt(1, Integer.parseInt(Technical_Name_id));
                Update_Reports_statement.setInt(2, Integer.parseInt(ListSpare_id));
                Update_Reports_statement.setInt(3, Integer.parseInt(Report_id_Text.getText()));
                int updateCount = Update_Reports_statement.executeUpdate();
                if (updateCount >= 1) {
                    JOptionPane.showMessageDialog(this, "Success");
                    Report_id_Text.setText("");
                    Floor.setText("");
                    Office.setText("");
                    ((DefaultListModel) Spare_Parts_List_Total.getModel()).clear();
                    Table.clearSelection();
                    Cost.setText("");
                    TotalCost = 0;
                    Total.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "We Have a issue ");
                }
            } catch (SQLException ex) {
                Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_SubmitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Technical_HomePage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            new Get_TABLE_Data("select * from TECHNICAL_DETAIL_VIEW Where condition_state = 'Available' ORDER BY id asc",
                    Table);
        } catch (SQLException ex) {
            Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            //Connection
            Connection c = Connection_fun.con();
            Statement statement = c.createStatement();

            // put the Technical Name in the combobox
            new Get_SQL_Data_ComboBox(
                    "select count(First_name) from EMPLOYEESPOSITION where employee_type = 'Technical'",
                    "select First_name || ' ' || Last_Name as Technical_Name from EMPLOYEESPOSITION where employee_type = 'Technical'",
                    "Technical_Name",
                    Technical_Name
            );

            // put the spare parts name in the List
            String Data_arr[];
            ResultSet rs;
            //Get The count
            rs = statement.executeQuery("select count(spare_parts_name) from spare_parts");
            rs.next();
            int var_count = rs.getInt(1);
            Data_arr = new String[var_count];
            //Get the data
            rs = statement.executeQuery("select spare_parts_name from spare_parts");
            int index = 0;
            while (rs.next()) {
                Data_arr[index] = rs.getString("spare_parts_name");
                index++;
            }
            Spare_Parts_List.setModel(new javax.swing.DefaultComboBoxModel(Data_arr));

            new Get_TABLE_Data("select * from TECHNICAL_DETAIL_VIEW Where condition_state = 'Available' ORDER BY id asc",
                    Table);

        } catch (SQLException ex) {
            Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // Get the selected row index in the table
        int selectedRow = Table.getSelectedRow();

        // Put the selected row index from the view to the model
        int modelRow = Table.convertRowIndexToModel(selectedRow);

        // Get the DefaultTableModel
        DefaultTableModel tbmodel = (DefaultTableModel) Table.getModel();

        // Use the modelRow to get values from the correct row in the model
        Report_id_Text.setText(tbmodel.getValueAt(modelRow, 0).toString());
        Floor.setText(tbmodel.getValueAt(modelRow, 3).toString());
        Office.setText(tbmodel.getValueAt(modelRow, 4).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        if (Spare_Parts_List.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "No item selected.");
        } else {
            //Put the Data in the Total List
            ListModel.addElement(Spare_Parts_List.getSelectedValue());
            Spare_Parts_List_Total.setModel(ListModel);
            //Add the total
            int Cost_Selection = Integer.parseInt(Cost.getText());
            TotalCost = TotalCost + Cost_Selection;
            Total.setText(TotalCost + "");

        }
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if (Spare_Parts_List_Total.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "No item selected.");
        } else {
            try {
                //Connection
                Connection c = Connection_fun.con();

                //Get the Cost With the Name Selection
                int Cost_Deleted = 0;
                String Selection = Spare_Parts_List_Total.getSelectedValue();
                PreparedStatement Cost_Statement = c.prepareStatement("select Cost from spare_parts where spare_parts_name=?");
                Cost_Statement.setObject(1, Selection);
                ResultSet Cost_result = Cost_Statement.executeQuery();
                if (Cost_result.next()) {
                    Cost_Deleted = Integer.parseInt(Cost_result.getString("Cost"));
                } else {
                    JOptionPane.showMessageDialog(this, "Spare Part not found.");
                }

                //Delete the Selection and - the Cost Deleted
                ListModel.removeElementAt(Spare_Parts_List_Total.getSelectedIndex());
                TotalCost = TotalCost - Cost_Deleted;
                Total.setText(TotalCost + "");
            } catch (SQLException ex) {
                Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_DeleteActionPerformed

    private void Spare_Parts_ListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_Spare_Parts_ListValueChanged
        try {
            //Connection
            Connection c = Connection_fun.con();
            Statement statement = c.createStatement();
            //Get the cost
            String Selection = Spare_Parts_List.getSelectedValue();
            PreparedStatement Cost_Statement = c.prepareStatement("select Cost from spare_parts where spare_parts_name=?");
            Cost_Statement.setObject(1, Selection);
            ResultSet Cost_result = Cost_Statement.executeQuery();
            if (Cost_result.next()) {
                Cost.setText(Cost_result.getString("Cost"));
            } else {
                JOptionPane.showMessageDialog(this, "Spare Part not found.");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Spare_Parts_ListValueChanged

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        DefaultTableModel ob = (DefaultTableModel) Table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        Table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(Search.getText()));
    }//GEN-LAST:event_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Technical_MaintenanceInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Technical_MaintenanceInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField Cost;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Floor;
    private javax.swing.JTextField Office;
    private javax.swing.JTextField Report_id_Text;
    private javax.swing.JTextField Search;
    private javax.swing.JList<String> Spare_Parts_List;
    private javax.swing.JList<String> Spare_Parts_List_Total;
    private javax.swing.JButton Submit;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> Technical_Name;
    private javax.swing.JTextField Total;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
